# Generated by Django 3.0.4 on 2024-05-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20240419_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
